package com.dmslob.contacts.service;

import org.springframework.stereotype.Service;

/**
 * SQL instructions within data.sql were generated by this array of names.
 */
@Service
public class NameGeneratorService {

    private String[] names = {
            "Liam", "Emma", "Noah", "Olivia", "William", "Ava", "James", "Isabella", "Oliver", "Sophia", "Benjamin",
            "Charlotte", "Elijah", "Mia", "Lucas", "Amelia", "Mason", "Harper", "Logan", "Evelyn", "Bobby"
    };

    private int nameCounter = 0;

    private String nextName() {
        if (nameCounter == names.length) {
            nameCounter = 0;
        }
        String name = names[nameCounter];
        nameCounter++;

        return name;
    }

    public String generate() {
        return nextName();
    }
}
